@baseUrl = http://localhost:3001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDUyNjIwMjQsImV4cCI6MTc0NTI2NTYyNH0.w_iMo2ymZcGpef8V16bbxEH-d3FMr7f0i9Znn-EEm3Y
GET {{baseUrl}}/sermons/?limit=10
Authorization: Bearer {{token}}
###
GET {{baseUrl}}/sermons/cm9r4o6fl00082lagcqwn3j32
###
POST {{baseUrl}}/sermons
Content-Type: application/json

{
    "title": "Sermão",
    "description": "Descrição do sermão",
    "speaker": "Pastor Bruno",
    "duration": "45 minutos",
    "date": "20 de Abril",
    "time": "10:00",
    "eventType": "evento",
    "references": [
        {
            "reference": "João 3:16",
            "text": "Referência Bíblica"
        },
        {
            "reference": "João 3:17",
            "text": "Outra referencia bíblica"
        }
    ],
    "contentSections": [
        {
            "type": "parágrafo",
            "content": "Paragrafo"
        },
        {
            "type": "header",
            "content": "Header"
        },
        {
            "type": "citação",
            "content": "Citação"
        }
    ]
}
###

PATCH {{baseUrl}}/sermons/cm9pu1zp700002l3o05iwqv3x/publish
Content-Type: application/json

{
    "published": true
}

###
PATCH {{baseUrl}}/sermons/cm9r4o6fl00082lagcqwn3j32
Content-Type: application/json

{
    "title": "Sermão",
    "description": "Descrição do sermão",
    "speaker": "Pastor Bruno",
    "duration": "45 minutos",
    "date": "20 de Abril",
    "time": "10:00",
    "eventType": "evento",
    "references": [
        {
            "reference": "João 3:16",
            "text": "Referência Bíblica"
        }
    ],
    "contentSections": [
        {
            "type": "parágrafo",
            "content": "Paragrafo"
        },
        {
            "type": "header",
            "content": "Header"
        },
        {
            "type": "citação",
            "content": "Citação"
        },
       
        {
            "type": "parágrafo",
            "content": "Outro Paragrafo"
        },
        {
            "type": "header",
            "content": "Outro header"
        },
        {
            "type": "citação",
            "content": "Outra Citação"
        }
    ]
}

###
DELETE {{baseUrl}}/sermons/63852226-993e-4b6e-a865-6ed3420ccd2d


###
#Usuários

GET {{baseUrl}}/users

###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "pastor@noah.com.br",
    "password": "123456" 
}
###
GET {{baseUrl}}/users/63852226-993e-4b6e-a865-6ed3420ccd2d


###
#Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "pastor@noah.com.br",
    "password": "123456"
}